image: node
stages:
  - build
  - test
  - deploy
cache:
  paths:
    - ./website/build
before_script:
  - whoami
build site:
  stage: build
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    when: on_success
    expire_in: 2h20min
    paths:
      - ./website/build/
  script:
    - npm --version
    - cd website
    - npm install
    - npm run build
deploy website:
  stage: deploy
  script:
    - npm install -g surge
    - surge --project /website/build/ --domain necessary-destruction.surge.sh
  after_script:
    - whoami

  environment:
    name: staging
    url: http://necessary-destruction.surge.sh