image: node
stages:
  - test
  - package
  - deploy

cache:
  paths:
    - ./website/build

before_script:
  - whoami
test site:
  stage: test
  before_script:
    - npm install -g broken-link-checker wait-on
  script:
    - cd website
    - npm install && npm run start &
    - wait-on https://necessary-destruction.surge.sh/ --timeout 30000
    - blc --recursive --exclude-external https://necessary-destruction.surge.sh/

package site:
  stage: build
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    when: on_success
    expire_in: 2h20min
    paths:
      - ./website/build/
  script:
    - npm --version
    - cd website
    - npm install
    - npm run build
deploy to staging:
  stage: deploy
  script:
    - npm install -g surge
    - surge --project ./website/build/test-site --domain necessary-destruction.surge.sh
  after_script:
    - whoami

  environment:
    name: staging
    url: http://necessary-destruction.surge.sh
  only:
    - develop