image: node
stages:
  - build
  - test
  - deploy
build site:
  stage: build
  artifacts:
    paths:
      - ./website/build/gitlabci
  script:
    - npm --version
    - cd website
    - npm install
    - npm run build