image: node
stages:
  - test
  - package
  - deploy

before_script:
  - whoami
test site:
  stage: test
  before_script:
    - npm install -g broken-link-checker wait-on
  script:
    - cd website
    - npm install && npm run start &
    - wait-on https://necessary-destruction.surge.sh/ --timeout 30000
    - blc --recursive --exclude-external https://necessary-destruction.surge.sh/
vulnerabilities check:
  stage: test
  script:
    - cd website && npm install && npm run scan

package site:
  stage: package
  cache:
    key: site-package
    policy: push
    paths:
      - ./website/build

  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    when: on_success
    expire_in: 2h20min
    paths:
      - ./website/build/
  script:
    - npm --version
    - cd website
    - npm install
    - npm run build


deploy site:
  stage: deploy
  variables:
   CNAME: necessary-destruction.surge.sh
   GIT_STRATEGY: none
  cache:
    key: site-package
    policy: pull
    paths:
      - ./website/build
  script:
    - npm install -g surge
    - surge --project ./website/build/test-site --domain ${CNAME}
  after_script:
    - whoami

  environment:
    name: staging
    url: http://${CNAME}
  only:
    - develop
deploy to production:
  stage: deploy
  variables:
    CNAME: necessary-destruction.surge.sh
    GIT_STRATEGY: none
  cache:
    key: site-package
    policy: pull
    paths:
      - ./website/build
  script:
    - npm install -g surge
    - surge --project ./website/build/test-site --domain ${CNAME}
  after_script:
    - whoami

  environment:
    name: staging
    url: http://${CNAME}
  only:
    - master